# Generated by Django 5.1 on 2024-08-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('valid_date', models.DateField()),
                ('working_hours', models.PositiveIntegerField()),
                ('salary', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='position/%Y/%m/%d/')),
                ('category', models.TextField(choices=[('CE', 'Computer engineer'), ('EE', 'Electronics engineer'), ('AC', 'Accountant'), ('SE', 'Secretary')], default='CE', max_length=2)),
            ],
        ),
    ]
