# Generated by Django 5.1 on 2024-08-19 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='employee',
            field=models.ManyToManyField(related_name='employee', to='user.user'),
        ),
        migrations.AddField(
            model_name='position',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
